---
- hosts: amazon-linux
  remote_user: ec2-user
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
    - name: Copy file 
      ansible.builtin.copy:
        src: /tmp/test.txt
        dest: /tmp
    - name: install apache server   # name of the playwh
      dnf:
        name: httpd
        state: latest
    - name: start and enable autostart of apache server
      systemd:
        name: httpd
        state: started
        enabled: yes
    - name: Status of httpd
      ansible.builtin.service:
        name: httpd
        state: reloaded  
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started
    - name: install docker   # name of the playwh
      dnf:
        name: docker
        state: latest
    - name: Start docker
      systemd:
        name: docker
        state: started
    - name: Status of docker
      ansible.builtin.service:
        name: docker
        state: reloaded